site_name: Crowdsec
nav:
  - Home: index.md
  - Getting Started:
#    - Glossary: getting_started/glossary.md
    - Concepts : getting_started/concepts.md
    - Install Crowdsec : getting_started/installation.md
    - Upgrade Crowdsec: getting_started/upgrades.md
    - Crowdsec Tour: getting_started/crowdsec-tour.md
  - User guide:
    - CLI: user_guide/cscli.md
    - Config management:
      - Collections: user_guide/configurations_management/collections.md
      - Parsers: user_guide/configurations_management/parsers.md
      - Enrichers: user_guide/configurations_management/enrichers.md
      - Scenarios: user_guide/configurations_management/scenarios.md
    - Decisions management: user_guide/decision_management.md
    - Bouncers & machines management: user_guide/bouncer_machine_management.md
    - Data sources config: 
       - Introduction: user_guide/data_sources/acquisition.md
       - Files: user_guide/data_sources/file.md
       - Journalctl: user_guide/data_sources/journalctl.md
       - Cloudwatch: user_guide/data_sources/cloudwatch.md
       - Syslog: user_guide/data_sources/syslog.md
    - Databases: user_guide/database.md
    - Network management: user_guide/network.md
    - Simulation management: user_guide/simulation_mode.md
    - Crowdsec forensic mode: user_guide/forensic_mode.md
    - Debugging: user_guide/debugging_configs.md
  - CLI:
    - Cscli: cscli/cscli.md
    - Alerts: cscli/cscli_alerts.md
    - Bouncers: cscli/cscli_bouncers.md
    - Collections: cscli/cscli_collections.md
    - Completion: cscli/cscli_completion.md
    - Config: cscli/cscli_config.md
    - Dashboard: cscli/cscli_dashboard.md
    - Decisions: cscli/cscli_decisions.md
    - Hub: cscli/cscli_hub.md
    - Machines: cscli/cscli_machines.md
    - Metrics: cscli/cscli_metrics.md
    - Parsers: cscli/cscli_parsers.md
    - Postoverflows: cscli/cscli_postoverflows.md
    - Scenarios: cscli/cscli_scenarios.md
    - Simulation: cscli/cscli_simulation.md
  - Local API: 
    - Introduction: localAPI/index.md
    - API Guide: localAPI/howto.md
    - Swagger: https://crowdsecurity.github.io/api_doc/index.html?urls.primaryName=LAPI" target="_blank
  - Observability:
    - Overview: observability/overview.md
    - Logs: observability/logs.md
    - Metrics: 
        - Prometheus: observability/prometheus.md
        - Command line: observability/command_line.md
    - Dashboard: observability/dashboard.md
  - Bouncers: bouncers/index.md
  - References:
    - Parsers, Scenarios etc.:
      - Stages format: references/stages.md
      - Parsers format: references/parsers.md
      - Scenarios format: references/scenarios.md
      - PostOverlows format: references/postoverflows.md
      - Enrichers format: references/enrichers.md
      - Collections format: references/collections.md
      - Expressions helpers: references/expressions.md
      - Patterns references: references/patterns-documentation.md
    - Configuration files:
      - Configuration format: references/crowdsec-config.md
      - Database format: references/database.md
      - Acquisition format: references/acquisition.md
      - Profiles format: references/profiles.md
      - Simulation configuration: references/simulation.md
    - Runtime objects:
      - Event object: references/events.md
      - Alert object: references/alerts.md
      - Decision object: references/decisions.md
  - Write Configurations:
    - Requirements: write_configurations/requirements.md
    - Acquisition: write_configurations/acquisition.md
    - Parsers: write_configurations/parsers.md
    - Scenarios: write_configurations/scenarios.md
    - Whitelists: write_configurations/whitelist.md
  - Upgrade V0.X to V1.X: migration.md
  - API Swagger : https://crowdsecurity.github.io/api_doc/index.html?urls.primaryName=LAPI" target="_blank
  - Hub : https://hub.crowdsec.net/" target="_blank
  - Releases : https://github.com/crowdsecurity/crowdsec/releases" target="_blank
  - Contributing:
    - Guide: contributing.md
  - FAQ:
    - Questions: faq.md


markdown_extensions:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - admonition
theme: 
  name: material
  logo: assets/images/crowdsec2.png
  favicon: assets/images/crowdsec2.png
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    - navigation.section
  palette:
    primary: "#3d85c6" 
  language: en
  font:
    text: Montserrat
  highlightjs: true
  hljs_languages:
      - yaml
repo_url: https://github.com/crowdsecurity/crowdsec
repo_name: GitHub
plugins:
    - search
    - macros
    - monorepo

extra:
    version:
        provider: mike
    swagger_url: "https://raw.githubusercontent.com/crowdsecurity/crowdsec/master/pkg/models/localapi_swagger.yaml"
###############################################################
### Bellow are defines for V1 and later of the documentation ##
###############################################################
    v1X:
      doc:
          new_issue: "[new documentation issue](https://github.com/crowdsecurity/crowdsec/issues/new)"
          discourse: "[CrowdSecurity discourse](http://discourse.crowdsec.net)"
          community: "[community](http://discourse.crowdsec.net)"
      hub:
          name: Crowdsec Hub
          htmlname: "[Crowdsec Hub](https://hub.crowdsec.net/)"
          url: "https://hub.crowdsec.net/"
          bouncers_url: "https://hub.crowdsec.net/browse/#bouncers"
          scenarios_url: "https://hub.crowdsec.net/browse/#configurations"
          parsers_url: "https://hub.crowdsec.net/browse/#configurations"
          collections_url: "https://hub.crowdsec.net/browse/#collections"
      crowdsec:
          name: crowdsec-agent
          Name: Crowdsec-agent
          url: https://github.com/crowdsecurity/crowdsec
          bugreport: "https://github.com/crowdsecurity/crowdsec/issues"
          download_url: https://github.com/crowdsecurity/crowdsec/releases
      lapi:
          name: local API (LAPI)
          Name: Local API (LAPI)
          Htmlname: "[Local API](localAPI/)"
          htmlname: "[local API](localAPI/)"
          url: localAPI/
          swagger: https://crowdsecurity.github.io/api_doc/index.html?urls.primaryName=LAPI
      cli:
          name: cscli
          Name: Cscli
          bin: cscli
          user_guide: "[cscli](user_guide/cscli.md)"
      config:
          crowdsec_dir: "/etc/crowdsec/"
          acquis_path: "/etc/crowdsec/acquis.yaml"
          crowdsec_config_file: "/etc/crowdsec/config.yaml"
      bouncers:
          name: bouncers
          Name: Bouncers
          url: "https://hub.crowdsec.net/browse/#bouncers"
          htmlname: "[bouncers](bouncers/)"
          Htmlname: "[bouncers](bouncers/)"
      metabase:
          name: metabase
          htmlName: "[dashboard](observability/dashboard.md)"
      wizard:
          name: wizard
          bin: "./wizard.sh"
          bugreport: "https://github.com/crowdsecurity/crowdsec/issues"
      ref:
          acquis: "[acquisition](references/acquisition.md)"
          parsers: "[parsers](references/parsers.md)"
          scenarios: "[scenarios](references/scenarios.md)"   
  # All the technical terms
      event:
          name: event
          Name: Event
          htmlname: "[event](getting_started/concepts.md#events)"
          Htmlname: "[Event](getting_started/concepts.md#events)" 
      expr:
          name: expr
          Name: Expr
          htmlname: "[expr](references/expressions.md)"
          Htmlname: "[Expr](references/expressions.md)"
      filter:
          name: filter
          Name: Filter
          htmlname: "[filter](references/parsers.md#filter)"
          Htmlname: "[Filter](references/parsers.md#filter)"
      onsuccess:
          name: onsuccess
          Name: Onsuccess
          htmlname: "[onsuccess](references/parsers.md#onsuccess)"  
          Htmlname: "[Onsuccess](references/parsers.md#onsuccess)"  
      profiles:
          htmlname: "[profiles](references/profiles.md)"
      simulation:
          htmlname: "[profiles](references/simulation.md)"
      statics:
          name: statics
          Name: Statics
          htmlname: "[statics](references/parsers.md#statics)"
          Htmlname: "[Statics](references/parsers.md#statics)"
      parsers:
          name: parsers
          Name: Parsers
          htmlname: "[parsers](getting_started/concepts.md#parsers)"
          Htmlname: "[Parsers](getting_started/concepts.md#parsers)"
      scenarios:
          name: scenarios
          Name: Scenarios
          htmlname: "[scenarios](getting_started/concepts.md#scenarios)"
          Htmlname: "[Scenarios](getting_started/concepts.md#scenarios)"
      collections:
          name: collections
          Name: Collections
          htmlname: "[collections](getting_started/concepts.md#collections)"
          Htmlname: "[Collections](getting_started/concepts.md#collections)"
      timeMachine:
          name: timeMachine
          Name: TimeMachine
          htmlname: "[timeMachine](getting_started/concepts.md#timemachine)"
          Htmlname: "[TimeMachine](getting_started/concepts.md#timemachine)"
      alert:
          name: alert
          Name: Alert
          htmlname: "[alert](getting_started/concepts.md#alerts)"
          Htmlname: "[Alert](getting_started/concepts.md#alerts)"
      decision:
          name: decision
          Name: Decision
          htmlname: "[decision](getting_started/concepts.md#decisions)"
          Htmlname: "[Decision](getting_started/concepts.md#decisions)"
      whitelists:
          name: whitelists
          Name: Whitelists
          htmlname: "[whitelists](write_configurations/whitelist.md)"
          Htmlname: "[Whitelists](write_configurations/whitelist.md)"
     #scenario stuff
      stage:
          name: stage
          Name: Stage
          htmlname: "[stage](getting_started/concepts.md#stages)"
          Htmlname: "[Stage](getting_started/concepts.md#stages)"
      leakspeed:
          name: leakspeed
          Name: Leakspeed
          htmlname: "[leakspeed](references/scenarios.md#leakspeed)"
          Htmlname: "[Leakspeed](references/scenarios.md#leakspeed)"
      capacity:
          name: capacity
          Name: Capacity
          htmlname: "[capacity](references/scenarios.md#capacity)"
          Htmlname: "[Capacity](references/scenarios.md#capacity)"
      duration:
          name: duration
          Name: Duration
          htmlname: "[duration](references/scenarios.md#duration)"
          Htmlname: "[Duration](references/scenarios.md#duration)"
      prometheus:
          name: prometheus
          htmlname: "[prometheus](https://github.com/prometheus/client_golang)"
      api:
          name: API
          htmlname: "[API](TBD)"
          topX:
              name: topX
              htmlname: "[topX](TBD)"

